{% set name = "cli-ui" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e6c80ada5b4b09c6701ca93daf31df8b70486c64348d1fc7f3288ef3bd0479c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry
  run:
    - colorama >=0.4.1
    - python >=3.7,<4.0
    - tabulate >=0.8.3
    - unidecode >=1.0.23

test:
  imports:
    - cli_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmerejkowsky/python-cli-ui
  summary: Build Nice User Interfaces In The Terminal
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
