{% set name = "cli-ui" %}
{% set version = "0.17.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cli-ui-{{ version }}.tar.gz
  sha256: 2f67e50cf474e76ad160c3e660bbad98bf8b8dfb8d847765f3a261b7e13c05fa

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - colorama >=0.4.1
    - python >={{ python_min }},<4.0
    - tabulate >=0.8.3
    - unidecode >=1.0.23

test:
  imports:
    - cli_ui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dmerejkowsky/python-cli-ui
  summary: Build Nice User Interfaces In The Terminal
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
